### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by baronvonvaderham** [AASHE/aashe-conference#19]
Duplicate: http://htmlstream.com/preview/unify-v1.8/page_contact_advanced.php

* Create form and form handler
* Create template
* May require a traditional view

**Comment by baronvonvaderham** [comment]
Not doing this. Not only is it proving more difficult than anticipated to style the form and to get the email backend working, Andrea just wants the "Contact Us" link to open an email for the user anyway.

**Comment by jessicaaasheaashe** [comment]
I agree.  I think that's easiest.  Since the is in that top level header,
could you set the link to mailto: conference@aashe.org?

Thanks@

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 3:30 PM, Scott Johnson <notifications@github.com>
wrote:

> Not doing this. Not only is it proving more difficult than anticipated to
> style the form and to get the email backend working, Andrea just wants the
> "Contact Us" link to open an email for the user anyway.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/19#issuecomment-204091450>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Precisely. It will also pre-populate the subject line with "AASHE 2016 Conference and Expo Inquiry".

It was supposed to be a '&', but html hates that character and I got tired of fighting with it >.<

**Comment by jessicaaasheaashe** [comment]
That sounds good.  Thanks!

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 3:50 PM, Scott Johnson <notifications@github.com>
wrote:

> Precisely. It will also pre-populate the subject line with "AASHE 2016
> Conference and Expo Inquiry".
>
> It was supposed to be a '&', but html hates that character and I got tired
> of fighting with it >.<
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/19#issuecomment-204098954>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
