### ISSUE TITLE
Home page layout

### ISSUE THREAD

**Issue by jessicaaasheaashe** [AASHE/aashe-conference#44]
There is this big white area between the left/right content boxes and the featured items content types.  How can we eliminate that space? 

![image](https://cloud.githubusercontent.com/assets/18149121/14156338/e8b0b760-f693-11e5-92fc-f5ff11220647.png)

**Comment by baronvonvaderham** [comment]
It's the size of the containers. I will see if I can change them to flex boxes so it fills the space better.

**Comment by jessicaaasheaashe** [comment]
@baronvonvaderham I also moved the "feature boxes" up on the home page because I wanted them higher up on the page but that messed up the layout of the left and right content boxes.  Could you help on that too?

**Comment by baronvonvaderham** [comment]
Where do you want them to appear? You dropped them in an uncontained region is the problem. I need to amend the template to add another region you can drop them into if you want them placed somewhere else, I laid the template out to match the one we had selected from Unify.

**Comment by jessicaaasheaashe** [comment]
The left and right content (i.e. schedule at a glance and image) should be
just under the feature boxes.

I think I am having trouble with these templates.  I would really love to
have blank page and be able to select each content type from a list I build
the pages. I think the regions are messing me up here.  I'm finding that
the content doesn't always fit the same template from page to page.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 12:46 PM, Scott Johnson <notifications@github.com>
wrote:

> Where do you want them to appear? You dropped them in an uncontained
> region is the problem. I need to amend the template to add another region
> you can drop them into if you want them placed somewhere else, I laid the
> template out to match the one we had selected from Unify.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/44#issuecomment-204015686>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
That's unfortunately not how the system is designed to work. To get each of these content types perfectly sized, oriented, and aligned, they must be placed inside of containers that dictate those attributes. They can't be hard-coded into the content types themselves, because then they will not be reusable and I have to code 6 new files every time we want a similar thing but positioned differently.

If we just have a blank template and you drop content in one after the other, it will just turn into a pile of text. They won't know to go next to, above, below, over, etc. the content piece before it.

The compromise is to make these content types render template fragments, then insert those into template regions that know what to do with them. The layout templates handle all of the positioning and orientation work to appropriately handle pieces of content designed to fit into those containers. That's why we can't just drop the main page slider into one of the column boxes, it's not designed to fit there. Many other content types, however, are more flexible, and can be dropped in many regions.

The idea was also that we were going to stick to the Unify templates we had selected as closely as possible so I don't have to continually modify templates and content pieces for each individual page.

After I get this next template and content type up, my next ticket, without fail, is redoing the content permissions. I think if I restrict them to their appropriate regions we can avoid this moving forward, and then if we run into a situation where you would like to see a piece of content in a different region, we can discuss it and if it is appropriate I can modify the template (or create a new one so we have options).

**Comment by baronvonvaderham** [comment]
Closing this for now to de-clutter the issues list. Moving forward we can make new tickets if there are any specific changes to be made to a template.

**Comment by jessicaaasheaashe** [comment]
OK I guess we can talk through the home page layout tomorrow.  Its not
really where I want it yet.  I was hoping the featured content boxes could
be moved to just below the call to action bar.

Jessica Chase, CAE
Director of Membership and Marketing
Association for the Advancement of Sustainability in Higher Education
(AASHE)
www.aashe.org | jessica@aashe.org | (888) 347-9997 ext. 126

On Thu, Mar 31, 2016 at 6:15 PM, Scott Johnson <notifications@github.com>
wrote:

> Closing this for now to de-clutter the issues list. Moving forward we can
> make new tickets if there are any specific changes to be made to a template.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/aashe-conference/issues/44#issuecomment-204154019>
>

-- 
Check out the new Campus Sustainability Hub <http://hub.aashe.org/>, an 
online library where members can quickly and easily find relevant resources.


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Ok, I'll make a specific ticket to move that then and take care of it later tonight.
